from .direction import DirectionRepos
from .discipline import DisciplineRepos
from .flow import FlowRepos
from .group import GroupRepos
from .teacher import TeacherRepos
from .type_direction import TypeDirectionRepos
from .type_lesson import TypeLessonRepos
from .room import RoomRepos
from .teacher_load_list import TeacherLoadListRepos
from .load_list import LoadListRepos
